#!/usr/bin/env python3
"""
bin2js.py — Convert raw binary terrain data to a JavaScript module.
Usage: python3 bin2js.py input.bin output.js
"""
import struct, sys, os

def convert(input_path, output_path):
    with open(input_path, 'rb') as f:
        data = f.read()

    offset = 0

    # Header
    magic = data[offset:offset+4]
    assert magic == b'HZTR', f"Bad magic: {magic}"
    offset += 4

    grid_w = struct.unpack_from('<I', data, offset)[0]; offset += 4
    grid_h = struct.unpack_from('<I', data, offset)[0]; offset += 4
    vstride = struct.unpack_from('<I', data, offset)[0]; offset += 4
    idx_count = struct.unpack_from('<I', data, offset)[0]; offset += 4
    _reserved = struct.unpack_from('<I', data, offset)[0]; offset += 4

    print(f"  Grid: {grid_w}x{grid_h}, vstride={vstride}, indices={idx_count}")

    # Read vertices
    vertex_count = grid_w * grid_h
    positions = []
    normals = []
    uvs = []
    colors = []

    for i in range(vertex_count):
        if offset + vstride > len(data):
            print(f"  WARNING: truncated at vertex {i}/{vertex_count}")
            break
        px, py, pz = struct.unpack_from('<fff', data, offset); offset += 12
        nx, ny, nz = struct.unpack_from('<fff', data, offset); offset += 12
        u, v = struct.unpack_from('<ff', data, offset); offset += 8
        # Color: 4 floats (R, G, B, A)
        cr = struct.unpack_from('<f', data, offset)[0]; offset += 4
        cg = struct.unpack_from('<f', data, offset)[0]; offset += 4
        cb = struct.unpack_from('<f', data, offset)[0]; offset += 4
        ca = struct.unpack_from('<f', data, offset)[0]; offset += 4

        positions.extend([round(px,4), round(py,4), round(pz,4)])
        normals.extend([round(nx,4), round(ny,4), round(nz,4)])
        uvs.extend([round(u,4), round(v,4)])
        colors.extend([round(cr,4), round(cg,4), round(cb,4), round(ca,4)])

    # Read indices
    indices = []
    for i in range(idx_count):
        if offset + 4 > len(data):
            print(f"  WARNING: truncated at index {i}/{idx_count}")
            break
        idx = struct.unpack_from('<I', data, offset)[0]; offset += 4
        indices.append(idx)

    print(f"  Read {len(positions)//3} vertices, {len(indices)//3} triangles")

    # Write JS module
    with open(output_path, 'w') as f:
        f.write('// AUTO-GENERATED by bin2js.py — DO NOT EDIT\n')
        f.write(f'// Source: {os.path.basename(input_path)}\n')
        f.write(f'// Grid: {grid_w}x{grid_h}, Vertices: {vertex_count}, Triangles: {len(indices)//3}\n')
        f.write(f'// Generated by x86-64 Assembly terrain generator\n\n')
        f.write(f'export const TERRAIN = {{\n')
        f.write(f'  gridW: {grid_w},\n')
        f.write(f'  gridH: {grid_h},\n')
        f.write(f'  vertexCount: {vertex_count},\n')
        f.write(f'  indexCount: {len(indices)},\n')
        f.write(f'  positions: new Float32Array({positions}),\n')
        f.write(f'  normals: new Float32Array({normals}),\n')
        f.write(f'  uvs: new Float32Array({uvs}),\n')
        f.write(f'  colors: new Float32Array({colors}),\n')
        f.write(f'  indices: new Uint32Array({indices}),\n')
        f.write(f'}};\n')

    out_size = os.path.getsize(output_path)
    print(f"  Written {output_path}: {out_size} bytes")

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} input.bin output.js")
        sys.exit(1)
    convert(sys.argv[1], sys.argv[2])
