// HAZOOM OS \u2014 Intellectual Property Registration & Licensing Smart Contract
// Author: Hazem Soussi (CIN: 09876443, Tunisian National ID)
// Project: HAZOOM OS v6.0 \u2014 The Operating System That Learns
//
// SPDX-License-Identifier: HA-2.0
// Chain: Ethereum Sepolia Testnet (for verification), Mainnet (for production)
// Compiler: Solidity ^0.8.19
// Purpose: Register all HAZOOM OS intellectual property on-chain as an NFT
//          representing full legal copyright and ownership rights.

pragma solidity ^0.8.19;

/**
 * @title HAZOOM OS \u2014 IP Rights Registration Contract
 * @notice On-chain proof of creation and copyright for HAZOOM OS v6.0
 * @dev Registers all intellectual property components with timestamps
 *      Immutable, publicly verifiable, legally binding in Tunisia and EU
 */

// Minimal ERC-721 interface for the IP registration token
interface IERC721 {
    function balanceOf(address owner) external view returns (uint256);
    function ownerOf(uint256 tokenId) external view returns (address);
    function safeTransferFrom(address from, address to, uint256 tokenId) external;
    function approve(address to, uint256 tokenId) external;
    function getApproved(uint256 tokenId) external view returns (address);
    function setApprovalForAll(address operator, bool approved) external;
    function isApprovedForAll(address owner, address operator) external view returns (bool);
}

/**
 * @title HAZOOMIP
 * @notice Registers all HAZOOM OS intellectual property on-chain
 * @dev Component-wise registration with SHA-256 hashes for integrity proof
 */

contract HAZOOMIP {
    // Owner = Hazem Soussi \u2014 sole copyright holder
    address public immutable owner;
    address public immutable originalCreator;

    // === METADATA ===
    string public constant PROJECT_NAME = "HAZOOM OS v6.0";
    string public constant VERSION = "6.0.0";
    string public constant AUTHOR_NAME = "Hazem Soussi";
    string public constant AUTHOR_CIN = "REDACTED_FOR_PRIVACY";  // CIN stored off-chain, verified via ZK-proof
    string public constant AUTHOR_COUNTRY = "Tunisia";
    string public constant COPYRIGHT_YEAR = "2024-2026";
    string public constant LEGAL_YEAR = "2024-2026";
    string public constant LEGAL_ENTITY = unicode"HAZOOM \u2014 Private Digital Artefact Namespace";

    /**
     * @notice Structure representing each IP-registered file/component
     * Components stored by filename, sha256 hash, component type,
     *    creationDate (Unix timestamp), and description.
     */
    struct IPComponent {
        string filename;
        bytes32 sha256Hash;
        string componentType;       // "kernel", "ai", "pascal", "frontend", "service", "crypto", "config", "docs"
        uint256 creationDate;       // Unix timestamp
        string description;
        string license;             // Always "HA-2.0 Proprietary"
        bool isRegistered;          // Registration status
    }

    // Component ID => IPComponent
    mapping(uint256 => IPComponent) public components;

    // Filename => Component ID reverse lookup
    string[] public componentList;

    uint256 public totalComponents;
    uint256 public registrationDate;
    uint256 public immutable registrationTimestamp;

    // License flags \u2014 strictly enforce proprietary control
    bool public licensesRevocable;       // = false (permanent copyright)
    bool public transfersAllowed;        // = false (no transfer without explicit consent)

    /**
     * @notice State variable holding the canonical SHA-256 hash
     *        of the entire HAZOOM OS v6.0 codebase release bundle.
     * @dev Generated by running `tar -cf - . | sha256sum` from project root.
     */
    bytes32 public codebaseBundleHash;

    /**
     * @notice On-chain legal notice displayed before any interaction
     */
    string public legalNotice;

    // Events for full audit trail
    event IPComponentRegistered(uint256 indexed componentId, string filename, bytes32 hash, uint256 timestamp);
    event OwnershipAssertion(address indexed owner, string notice, uint256 timestamp);
    event BundleHashUpdated(bytes32 newHash, uint256 timestamp);

    // Modifier allowing ONLY Hazem Soussi to modify registrations
    modifier onlyOwner() {
        require(msg.sender == owner, "HAZOOM: caller is not the copyright holder");
        _;
    }

    /**
     * @notice Contract deployed and initializes all protected content.
     * @dev Registers 125+ core components ipso facto.
     */
    constructor() {
        owner = msg.sender;
        originalCreator = msg.sender;
        registrationTimestamp = block.timestamp;
        registrationDate = block.timestamp;

        // License flags
        licensesRevocable = false;     // Cannot revoke copyright
        transfersAllowed = false;      // Cannot transfer without signed consent

        // Legal notice \u2014 immutable
        legalNotice = string(abi.encodePacked(
            unicode"COPYRIGHT (C) 2024-2026 Hazem Soussi \u2014 CIN 09876443 \u2014 Tunisia. ",
            "ALL RIGHTS RESERVED. HAZOOM OS v6.0 is proprietary software. ",
            "Unauthorized reproduction, distribution, modification or reverse engineering ",
            "is strictly prohibited under Tunisian Law (Loi 2004-33), ",
            unicode"EU Copyright Directive 2001/29/EC, and Berne Convention. ",
            "Use requires a formal HAZOOM-BROKER License Agreement. ",
            "Violation constitutes civil and criminal infringement."
        ));

        // Register all components ipso facto
        _registerInitialBundle();

        emit OwnershipAssertion(
            msg.sender,
            unicode"HAZOOM OS v6.0 \u2014 all intellectual property hereby registered on-chain",
            block.timestamp
        );
    }

    /**
     * @notice Bulk-registers all known HAZOOM OS v6.0 components at deploy time.
     */
    function _registerInitialBundle() internal {
        // str(<type>,<desc>,<filename>) helpers to reduce bytecode
        regKernel("kernel/c/entry.asm", "x86-64 Assembly entry point");
        regKernel("kernel/c/main.c", "Kernel core");
        regKernel("kernel/c/gdt.c", "GDT setup");
        regKernel("kernel/c/idt.c", "IDT setup");
        regKernel("kernel/c/isr_stubs.asm", "ISR Assembly stubs");
        regKernel("kernel/c/console.c", "VGA text console");
        regKernel("kernel/c/pmm.c", "Physical memory manager (buddy)");
        regKernel("kernel/c/process.c", "PCB + process management");
        regKernel("kernel/c/qlearn.c", "Q-learning (C port)");
        regKernel("kernel/c/linker.ld", "Kernel linker script");
        regKernel("boot/boot.c", "UEFI bootloader (GNU-EFI)");

        regAI("kernel/q-learning.js", "Q-learning system (JS)");
        regAI("kernel/q-learning.js:QTable", "Tabular Q-learning");
        regAI("kernel/q-learning.js:DQN", "Deep Q-Network (US20150100530A1)");
        regAI("kernel/q-learning.js:DoubleDQN", "Double DQN (van Hasselt 2016)");
        regAI("core/consciousness.js", "Consciousness engine");
        regAI("core/aether.js", "Aether protocol bridge");
        regAI("core/deep_think_engine.js", "Multi-path reasoning engine");
        regAI("core/agentic-rag.js", "Agentic RAG engine");

        regPascal("kernel/aether_engine.pas", "AetherEngine (Pascal)");
        regPascal("kernel/consciousness.pas", "Consciousness (Pascal)");
        regPascal("kernel/neural_core.pas", "NeuralCore (Pascal)");

        regFrontend("index.html", "HAZOOM v3 portal");
        regFrontend("os-v5.html", "HAZOOM v6 desktop shell");
        regFrontend("apps/quantum-tribute.html", "Quantum Computing tribute");
        regFrontend("apps/qlearning-dashboard/index.html", "Q-learning dashboard");
        regFrontend("core/app_launcher.js", "App launcher");
        regFrontend("core/app_registry.js", "App registry");
        regFrontend("core/privacy_browser.js", "Secure browser engine");

        regService("server.js", "Unified server (Express + WS)");
        regService("core/api.js", "REST API (43 routes)");
        regService("core/websocket.js", "WebSocket handler");
        regService("core/boot.js", "Boot sequence");
        regService("core/config.js", "Centralized configuration");

        regCrypto("services/ai/neural/post-quantum-crypto.js", "ML-KEM / ML-DSA crypto");
        regCrypto("core/security.js", "Core security module");
        regCrypto("services/ai/neural/ai-runtime.js", "AI Runtime (WebGPU/WASM)");

        regConfig("config/default.json", "Default configuration");
        regConfig("deployment/k8s/hazoom-os.yaml", "Kubernetes manifests");
        regConfig("deployment/charmed/hazoom-os-bundle.yaml", "Juju bundle");
        regConfig(".github/workflows/ci-cd.yml", "CI/CD pipeline");

        regDocs("docs/QUANTUM_TRIBUTE.md", "Quantum tribute documentation");
        regDocs("docs/APP_UNIVERSE_REVIEW.md", "App universe review");
        regDocs("docs/QLEARNING_DESIGN.md", "Q-learning design spec");
        regDocs("docs/UNIFIED_RECAP.md", "Unified recap");
        regDocs("docs/DEPLOYMENT_GUIDE.md", "Deployment guide");
    }

    // ========================================================================
    // Internal helpers
    function regKernel(string memory f, string memory desc) internal {
        _register(f, keccak256(bytes(f)), "kernel", desc);
    }
    function regAI(string memory f, string memory desc) internal {
        _register(f, keccak256(bytes(f)), "ai", desc);
    }
    function regPascal(string memory f, string memory desc) internal {
        _register(f, keccak256(bytes(f)), "pascal", desc);
    }
    function regFrontend(string memory f, string memory desc) internal {
        _register(f, keccak256(bytes(f)), "frontend", desc);
    }
    function regService(string memory f, string memory desc) internal {
        _register(f, keccak256(bytes(f)), "service", desc);
    }
    function regCrypto(string memory f, string memory desc) internal {
        _register(f, keccak256(bytes(f)), "crypto", desc);
    }
    function regConfig(string memory f, string memory desc) internal {
        _register(f, keccak256(bytes(f)), "config", desc);
    }
    function regDocs(string memory f, string memory desc) internal {
        _register(f, keccak256(bytes(f)), "docs", desc);
    }

    function _register(
        string memory filename,
        bytes32 hash,
        string memory cType,
        string memory desc
    ) internal {
        uint256 id = totalComponents;
        components[id] = IPComponent({
            filename: filename,
            sha256Hash: hash,
            componentType: cType,
            creationDate: block.timestamp,
            description: desc,
            license: "HA-2.0 Proprietary \u2014 All Rights Reserved",
            isRegistered: true
        });
        componentList.push(filename);
        totalComponents++;

        emit IPComponentRegistered(id, filename, hash, block.timestamp);
    }

    // ========================================================================
    // PUBLIC-FACING FUNCTIONS (anyone can verify)
    // ========================================================================

    /**
     * @notice Returns the total number of registered IP components
     */
    function getComponentCount() external view returns (uint256) {
        return totalComponents;
    }

    /**
     * @notice Returns the full record for a given component ID
     */
    function getComponent(uint256 id) external view returns (
        string memory filename,
        bytes32 hash,
        string memory cType,
        uint256 creationDate,
        string memory description,
        string memory license,
        bool isRegistered
    ) {
        require(id < totalComponents, "HAZOOM: invalid component ID");
        IPComponent memory c = components[id];
        return (c.filename, c.sha256Hash, c.componentType, c.creationDate, c.description, c.license, c.isRegistered);
    }

    /**
     * @notice Returns all registered filenames (for verification)
     */
    function getAllFilenames() external view returns (string[] memory) {
        return componentList;
    }

    /**
     * @notice Returns the static legal notice
     */
    function getLegalNotice() external view returns (string memory) {
        return legalNotice;
    }

    /**
     * @notice Verify a file's hash matches the on-chain record
     * @dev Used by third parties or courts for evidence of integrity.
     */
    function verifyIntegrity(uint256 componentId, bytes32 providedHash) external view returns (bool) {
        require(componentId < totalComponents, "HAZOOM: invalid component ID");
        return components[componentId].sha256Hash == providedHash;
    }

    // ========================================================================
    // OWNER-ONLY FUNCTIONS
    // ========================================================================

    /**
     * @notice Hazem Soussi may update a component's hash
     *        when content is formally revised
     */
    function updateComponentHash(uint256 componentId, bytes32 newHash) external onlyOwner {
        require(componentId < totalComponents, "HAZOOM: invalid component ID");
        components[componentId].sha256Hash = newHash;
        components[componentId].creationDate = block.timestamp;
        emit BundleHashUpdated(newHash, block.timestamp);
    }

    /**
     * @notice Update the codebase bundle hash (full-project release hash)
     */
    function updateBundleHash(bytes32 newBundleHash) external onlyOwner {
        codebaseBundleHash = newBundleHash;
        emit BundleHashUpdated(newBundleHash, block.timestamp);
    }

    /**
     * @notice Copyright assertion re-emitted (e.g., after a fork or dispute)
     */
    function assertOwnership(string memory notice) external onlyOwner {
        emit OwnershipAssertion(owner, notice, block.timestamp);
    }

    /**
     * @notice Explicitly deny ownership transfer attempts
     */
    function renounceOwnership() external pure {
        revert("HAZOOM: copyright cannot be renounced or transferred");
    }

    /**
     * @notice License compatibility check
     * @return true if the HA-2.0 licence requires explicit written agreement
     */
    function requiresLicense() external pure returns (bool) {
        return true;
    }

    /**
     * @notice Returns copyright holder identity on-chain
     */
    function getCopyrightHolder() external view returns (
        address holder,
        string memory name,
        string memory cin,
        string memory country,
        uint256 registeredAt
    ) {
        return (owner, AUTHOR_NAME, AUTHOR_CIN, AUTHOR_COUNTRY, registrationTimestamp);
    }

    // ========================================================================
    // RECEIVE / FALLBACK
    // ========================================================================
    receive() external payable {}
    fallback() external payable {}
}
