/* 
 * Hazoom Emoji Mapping
 * Auto-generated by migrate_assets.py
 * Date: 2025-10-31
 */

// Kangourou emotions (13 variations)
export const KANGOUROU_EMOTIONS = {
  WELCOME: 'assets/emojis/kangourou/hazoom_emoji_1.svg',
  HAPPY: 'assets/emojis/kangourou/hazoom_emoji_2.svg',
  SURPRISED: 'assets/emojis/kangourou/hazoom_emoji_3.svg',
  THINKING: 'assets/emojis/kangourou/hazoom_emoji_4.svg',
  MOTIVATED: 'assets/emojis/kangourou/hazoom_emoji_5.svg',
  CONGRATULATIONS: 'assets/emojis/kangourou/hazoom_emoji_6.svg',
  SAD: 'assets/emojis/kangourou/hazoom_emoji_7.svg',
  CONFUSED: 'assets/emojis/kangourou/hazoom_emoji_8.svg',
  TIRED: 'assets/emojis/kangourou/hazoom_emoji_9.svg',
  EXCITED: 'assets/emojis/kangourou/hazoom_emoji_10.svg',
  STUDYING: 'assets/emojis/kangourou/hazoom_emoji_11.svg',
  LOVING: 'assets/emojis/kangourou/hazoom_emoji_12.svg',
  COOL: 'assets/emojis/kangourou/hazoom_emoji_13.svg'
};

// Profile avatars (6 animals)
export const PROFILE_AVATARS = {
  BEAR: {
    path: 'assets/emojis/profiles/bear.svg',
    name: 'Ours',
    personality: 'Doux et protecteur',
    emoji: '🐻'
  },
  CAT: {
    path: 'assets/emojis/profiles/cat.svg',
    name: 'Chat',
    personality: 'Curieux et joueur',
    emoji: '🐱'
  },
  FROG: {
    path: 'assets/emojis/profiles/frog.svg',
    name: 'Grenouille',
    personality: 'Joyeux et énergique',
    emoji: '🐸'
  },
  LION: {
    path: 'assets/emojis/profiles/lion.svg',
    name: 'Lion',
    personality: 'Courageux et leader',
    emoji: '🦁'
  },
  OWL: {
    path: 'assets/emojis/profiles/owl.svg',
    name: 'Hibou',
    personality: 'Sage et studieux',
    emoji: '🦉'
  },
  TIGER: {
    path: 'assets/emojis/profiles/tiger.svg',
    name: 'Tigre',
    personality: 'Aventureux et sportif',
    emoji: '🐯'
  }
};

// Icons mapping (34 functional icons)
export const ICONS = {
  AGENDA: 'assets/icons/png/Icon_Hazoom_00.png',
  NOTIFICATION: 'assets/icons/png/Icon_Hazoom_01.png',
  QUIZ: 'assets/icons/png/Icon_Hazoom_02.png',
  PROGRESS: 'assets/icons/png/Icon_Hazoom_03.png',
  PROFILE: 'assets/icons/png/Icon_Hazoom_04.png',
  SETTINGS: 'assets/icons/png/Icon_Hazoom_05.png',
  FAVORITE: 'assets/icons/png/Icon_Hazoom_06.png',
  HOMEWORK: 'assets/icons/png/Icon_Hazoom_07.png',
  CHAT: 'assets/icons/png/Icon_Hazoom_08.png',
  SEARCH: 'assets/icons/png/Icon_Hazoom_09.png',
  // Add mappings for icons 10-33 as needed
};

// Helper function to get kangourou emoji by emotion
export function getKangourouEmoji(emotion) {
  return KANGOUROU_EMOTIONS[emotion.toUpperCase()] || KANGOUROU_EMOTIONS.WELCOME;
}

// Helper function to get random kangourou emoji
export function getRandomKangourou() {
  const emotions = Object.values(KANGOUROU_EMOTIONS);
  return emotions[Math.floor(Math.random() * emotions.length)];
}

// Helper function to get profile avatar by animal
export function getProfileAvatar(animal) {
  const avatar = PROFILE_AVATARS[animal.toUpperCase()];
  return avatar ? avatar.path : null;
}

// Helper function to list all available avatars
export function getAllAvatars() {
  return Object.entries(PROFILE_AVATARS).map(([key, value]) => ({
    id: key.toLowerCase(),
    ...value
  }));
}
